name: Amul Stock Checker

on:
  schedule:
    # Every 15 mins between 9AM to 12PM India time (3:30-6:30 UTC)
    - cron: '*/15 3-6 * * *'
  workflow_dispatch:

jobs:
  check-stock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run stock checker
        run: python main.py
